# Generated by Django 3.2 on 2022-03-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanimage',
            name='stress_level',
            field=models.FloatField(default=0),
        ),
    ]
