# Generated by Django 3.2 on 2022-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_scanimage_stress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanimage',
            name='stress_level',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
